// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgHav4r2kysoftpBuQ8IPIDGUrkQydWA',
    appId: '1:398534479066:web:6443657351658bd70769e3', // Placeholder - please REPLACE with actual Web App ID
    messagingSenderId: '398534479066',
    projectId: 'unibuy-e0fae',
    authDomain: 'unibuy-e0fae.firebaseapp.com',
    storageBucket: 'unibuy-e0fae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgHav4r2kysoftpBuQ8IPIDGUrkQydWA',
    appId: '1:398534479066:android:1821c4fe52159eda0769e3',
    messagingSenderId: '398534479066',
    projectId: 'unibuy-e0fae',
    storageBucket: 'unibuy-e0fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkgHav4r2kysoftpBuQ8IPIDGUrkQydWA',
    appId: '1:398534479066:ios:e223c28723c6feda0769e3', // Placeholder
    messagingSenderId: '398534479066',
    projectId: 'unibuy-e0fae',
    storageBucket: 'unibuy-e0fae.firebasestorage.app',
    iosBundleId: 'com.example.unibuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkgHav4r2kysoftpBuQ8IPIDGUrkQydWA',
    appId: '1:398534479066:ios:e223c28723c6feda0769e3', // Placeholder
    messagingSenderId: '398534479066',
    projectId: 'unibuy-e0fae',
    storageBucket: 'unibuy-e0fae.firebasestorage.app',
    iosBundleId: 'com.example.unibuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkgHav4r2kysoftpBuQ8IPIDGUrkQydWA',
    appId: '1:398534479066:web:6443657351658bd70769e3', // Placeholder
    messagingSenderId: '398534479066',
    projectId: 'unibuy-e0fae',
    authDomain: 'unibuy-e0fae.firebaseapp.com',
    storageBucket: 'unibuy-e0fae.firebasestorage.app',
  );
}
